// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type User struct {
	ID         string
	Name       string
	Password   string
	Provider   string
	Providerid string
}
